### ISSUE TITLE
Bug : Formatage équations

### ISSUE THREAD

**Issue by vicllo** [MarcdeFalco/MarcdeFalco.github.io#1]
Dans la page [https://marcdefalco.github.io/chap_analyse_algorithme.html](url)
Fin du paragraphe 2.2,

Problème lié au formatage mathématique qui débute avec l'apparition des "$", entrainant probablement un décalage de la reconnaissance des marqueurs.

![image](https://user-images.githubusercontent.com/61057360/127745163-1f27548c-8c75-4bfc-b2a4-a34881fee736.png)

**Comment by MarcdeFalco** [comment]
Corrigé, merci.
